### ISSUE TITLE
Logging an exception from Facade crashes Logary (proper)

### ISSUE THREAD

**Issue by adamchester** [logary/logary#168]
I've created a [sample that crashes Logary (proper)](https://github.com/adamchester/logary/commit/9e42bd782fa8dce202d54eba81b5f37d636c344e).

The stacktrace follows:
```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Method may only be called on a Type for which Type.IsGenericParameter is true.
   at System.RuntimeType.get_DeclaringMethod()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Logary.Internals.Map.ofObject@251-5.Invoke(PropertyInfo pi) in C:\My\repo\logary-2\src\Logary\Internals.fs:line 251
   at Logary.Internals.Map.ofObject@204.Invoke(Object _arg2) in C:\My\repo\logary-2\src\Logary\Internals.fs:line 251
   at Logary.ValueModule.OfObject(Object _arg1) in C:\My\repo\logary-2\src\Logary\DataModel.fs:line 248
   at Logary.ValueModule.OfObject@250-4.Invoke(String _arg1, Object v) in C:\My\repo\logary-2\src\Logary\DataModel.fs:line 250
   at Microsoft.FSharp.Collections.MapTreeModule.mapiOpt[a,b,c](FSharpFunc`3 f, MapTree`2 m)
   at Microsoft.FSharp.Collections.MapTreeModule.mapiOpt[a,b,c](FSharpFunc`3 f, MapTree`2 m)
   at Microsoft.FSharp.Collections.FSharpMap`2.Map[b](FSharpFunc`2 f)
   at Logary.ValueModule.OfObject(Object _arg1) in C:\My\repo\logary-2\src\Logary\DataModel.fs:line 248
   at Logary.ValueModule.OfObject@238-2.Invoke(Object _arg1) in C:\My\repo\logary-2\src\Logary\DataModel.fs:line 238
   at Microsoft.FSharp.Collections.IEnumerator.map@111.DoMoveNext(b& )
   at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Logary.ValueModule.OfObject(Object _arg1) in C:\My\repo\logary-2\src\Logary\DataModel.fs:line 236
   at Logary.ValueModule.OfObject@250-4.Invoke(String _arg1, Object v) in C:\My\repo\logary-2\src\Logary\DataModel.fs:line 250
   at Microsoft.FSharp.Collections.MapTreeModule.mapiOpt[a,b,c](FSharpFunc`3 f, MapTree`2 m)
   at Microsoft.FSharp.Collections.MapTreeModule.mapiOpt[a,b,c](FSharpFunc`3 f, MapTree`2 m)
   at Microsoft.FSharp.Collections.MapTreeModule.mapiOpt[a,b,c](FSharpFunc`3 f, MapTree`2 m)
   at Microsoft.FSharp.Collections.MapTreeModule.mapiOpt[a,b,c](FSharpFunc`3 f, MapTree`2 m)
   at Microsoft.FSharp.Collections.MapTreeModule.mapiOpt[a,b,c](FSharpFunc`3 f, MapTree`2 m)
   at Microsoft.FSharp.Collections.FSharpMap`2.Map[b](FSharpFunc`2 f)
   at Logary.ValueModule.OfObject(Object _arg1) in C:\My\repo\logary-2\src\Logary\DataModel.fs:line 248
   at Logary.ValueModule.OfObject@250-4.Invoke(String _arg1, Object v) in C:\My\repo\logary-2\src\Logary\DataModel.fs:line 250
   at Microsoft.FSharp.Collections.MapTreeModule.mapiOpt[a,b,c](FSharpFunc`3 f, MapTree`2 m)
   at Microsoft.FSharp.Collections.MapTreeModule.mapiOpt[a,b,c](FSharpFunc`3 f, MapTree`2 m)
   at Microsoft.FSharp.Collections.MapTreeModule.mapiOpt[a,b,c](FSharpFunc`3 f, MapTree`2 m)
   at Microsoft.FSharp.Collections.FSharpMap`2.Map[b](FSharpFunc`2 f)
   at Logary.ValueModule.OfObject(Object _arg1) in C:\My\repo\logary-2\src\Logary\DataModel.fs:line 248
   at Logary.ValueModule.OfObject@238-2.Invoke(Object _arg1) in C:\My\repo\logary-2\src\Logary\DataModel.fs:line 238
   at Microsoft.FSharp.Collections.IEnumerator.map@111.DoMoveNext(b& )
   at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Logary.ValueModule.OfObject(Object _arg1) in C:\My\repo\logary-2\src\Logary\DataModel.fs:line 236
   at Logary.MessageModule.SetFieldsFromMap@1146.Invoke(KeyValuePair`2 _arg1) in C:\My\repo\logary-2\src\Logary\DataModel.fs:line 1146
   at Microsoft.FSharp.Collections.IEnumerator.map@111.DoMoveNext(b& )
   at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Logary.MessageModule.SetFieldsFromMap(FSharpMap`2 m, Message msg) in C:\My\repo\logary-2\src\Logary\DataModel.fs:line 1145
   at Logary.Adapters.Facade.LoggerAdapter.toMsg(String[] fallbackName, Object o) in C:\My\repo\logary-2\src\adapters\Logary.Adapters.Facade\Logary.Adapters.Facade.fs:line 59
   at Logary.Adapters.Facade.LoggerAdapter.|Log|LogWithAck|LogSimple|(IInvocation _arg1_0, String[] _arg1_1) in C:\My\repo\logary-2\src\adapters\Logary.Adapters.Facade\Logary.Adapters.Facade.fs:line 90
   at Logary.Adapters.Facade.LoggerAdapter.I.Castle-DynamicProxy-IInterceptor-Intercept(IInvocation invocation) in C:\My\repo\logary-2\src\adapters\Logary.Adapters.Facade\Logary.Adapters.Facade.fs:line 143
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Libryy.Core.simpleWorkThatCatchesAndLogsAnErrorAndException(Logger logger) in C:\My\repo\logary-2\examples\Libryy\Libryy.fs:line 43
   at Servizz.Program.main(String[] argv) in C:\My\repo\logary-2\examples\Servizz\Program.fs:line 34
W 2016-08-01T10:38:03.0290450+00:00: Hey haf! [Libryy.Core.work]
  user => "haf"
D 2016-09-25T03:19:38.7369499+00:00: Got 42 from Libryy [Libryy]
  workResult => 42
Press any key to continue . . .
```

**Comment by adamchester** [comment]
There are a few things going on here, and I'm currently trying to address them. If all goes well, I will raise a PR soon.

**Comment by haf** [comment]
Cool, nice catch (haha)
