### ISSUE TITLE
More tests for fetching perf counters on Windows

### ISSUE THREAD

**Issue by haf** [logary/logary#207]
Also consider the case when we spawn and then exit and spawn processes again.

 - Objects.Mutexes for example

**Comment by haf-lynx** [comment]
```
Unhandled exception: System.InvalidOperationException: Instance 'Lynx.Mimer.MimerService.Host#1' does not exist in the specified Category.
   at System.Diagnostics.CounterDefinitionSample.GetInstanceValue(String instanceName)
   at System.Diagnostics.PerformanceCounter.NextSample()
   at System.Diagnostics.PerformanceCounter.NextValue()
   at <StartupCode$Logary-Metrics-WinPerfCounters>.$WinPerfCounter.f@1(WinPerfCounterInstance x, String instance)
   at Logary.Metrics.WinPerfCounterInstance.nextValues()
   at Logary.Metrics.WinPerfCounterModule.Helpers.toValue(WinPerfCounterInstance pc)
   at Logary.Metrics.WinPerfCounters.ofCounters@134.Invoke(WinPerfCounterInstance[] state)
   at Logary.Metric.x2yJ@1-2[state](FSharpFunc`2 handleTick, Metric self, Job`1 emptyResult, state state, FSharpList`1 msgs, Unit _arg4)
   at Logary.Metric.x2xJ@56-6.Do(Unit x)
   at Hopac.Core.ContBind`2.DoWork(Worker& wr)
   at Hopac.Core.Worker.Run(Scheduler sr, Int32 me)
No other causes.
```

**Comment by haf** [comment]
.Net Core has no wpc support and I'd prefer to turn Logary more cross platform, not less.
