### ISSUE TITLE
DB.Migrations doesn't always use the correct schema

### ISSUE THREAD

**Issue by btrepp** [logary/logary#264]
For SQLServer in
Logary.Targets.DB.Migrations/Migrations.fs

```
 base.Create
      .Table(Defaults.GaugesTable).InSchema(Defaults.Schema)

      .WithColumn("Value").AsDouble().NotNullable()
        .WithColumnDescription("The value of the measure.")

      |> SharedBetweenTables.messageStructure

    |> ignore

    // if you're just shipping
    base.Create.Index("IX_Gauges_EpochNanos").OnTable(Defaults.GaugesTable)
      .OnColumn("EpochNanos").Descending().WithOptions().NonClustered()
    |> ignore
```

The gauges table gets created with the "Logary" schema, but then an index is added without specifying the schema (this defaults to dbo)

Which gives, and leaves a logary schema with a single table VersionInfo

```
[+] Beginning Transaction
[+] Committing Transaction
[+] Beginning Transaction
[10:34:26 INF] /* CreateSchema Logary */
[10:34:26 INF]

[10:34:26 INF]

[10:34:26 INF]

[+] Committing Transaction
[10:34:26 INF] /* VersionSchemaMigration migrating ========================================== */
[10:34:26 INF]

[10:34:26 INF] /* VersionSchemaMigration migrated */
[10:34:26 INF]

[10:34:26 INF]

[10:34:26 INF] /* VersionMigration migrating ================================================ */
[10:34:26 INF]

[10:34:26 INF]

[10:34:26 INF] /* CreateTable VersionInfo */
[10:34:26 INF]

[10:34:26 INF]

[10:34:26 INF] /* VersionMigration migrated */
[10:34:26 INF]

[10:34:26 INF]

[+] Beginning Transaction
[10:34:27 INF] /* VersionUniqueMigration migrating ========================================== */
[10:34:27 INF]

[10:34:27 INF]

[10:34:27 INF] /* CreateIndex VersionInfo (Version) */
[10:34:27 INF]

[10:34:27 INF]

[10:34:27 INF] /* AlterTable VersionInfo */
[10:34:27 INF]

[10:34:27 INF]

[[+] Committing Transaction
10:34:27 INF]

[10:34:27 INF] /* CreateColumn VersionInfo AppliedOn DateTime */
[10:34:27 INF]

[10:34:27 INF]

[10:34:27 INF] /* VersionUniqueMigration migrated */
[10:34:27 INF]

[+] Beginning Transaction
[10:34:27 INF] /* VersionDescriptionMigration migrating ===================================== */
[10:34:27 INF]

[[+] Committing Transaction
10:34:27 INF]

[10:34:27 INF] /* AlterTable VersionInfo */
[10:34:27 INF]

[10:34:27 INF]

[10:34:27 INF] /* CreateColumn VersionInfo Description String */
[10:34:27 INF]

[10:34:27 INF]

[10:34:27 INF]

[10:34:27 INF] /* VersionDescriptionMigration migrated */
[10:34:27 INF]

[10:34:27 [+] Beginning Transaction
INF] /* 1: GaugesTable migrating ================================================== */
[10:34:27 INF]

[10:34:27 INF]

[10:34:27 INF] /* CreateTable Gauges */
[10:34:27 INF]

[10:34:27 INF]

[10:34:27 INF] /* CreateIndex Gauges (EpochNanos) */
[10:34:27 INF]

[10:34:27 [+] Rolling back transaction
INF] /* !!! An error occured executing the following sql:
CREATE INDEX [IX_Gauges_EpochNanos] ON [dbo].[Gauges] ([EpochNanos] DESC)
The error was Cannot find the object "dbo.Gauges" because it does not exist or you do not have permissions.
 */
[10:34:27 INF]

[10:34:27 INF] /* !!! Cannot find the object "dbo.Gauges" because it does not exist or you do not have permissions. */
[10:34:27 INF]

[10:34:27 ERR] Unhandled error
System.Exception: An error occured executing the following sql:
CREATE INDEX [IX_Gauges_EpochNanos] ON [dbo].[Gauges] ([EpochNanos] DESC)
The error was Cannot find the object "dbo.Gauges" because it does not exist or you do not have permissions.

   at FluentMigrator.Runner.Processors.SqlServer.SqlServerProcessor.ExecuteNonQuery(String sql) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\Processors\SqlServer\SqlServerProcessor.cs:line 184
   at FluentMigrator.Runner.Processors.SqlServer.SqlServerProcessor.Process(String sql) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\Processors\SqlServer\SqlServerProcessor.cs:line 163
   at FluentMigrator.Runner.Processors.ProcessorBase.Process(CreateIndexExpression expression) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\Processors\ProcessorBase.cs:line 95
   at FluentMigrator.Expressions.CreateIndexExpression.ExecuteWith(IMigrationProcessor processor) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator\Expressions\CreateIndexExpression.cs:line 46
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass72_0.<ExecuteExpressions>b__1() in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 489
   at FluentMigrator.Runner.StopWatch.Time(Action action) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\StopWatch.cs:line 57
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 502
   at FluentMigrator.Runner.MigrationRunner.ExecuteMigration(IMigration migration, Action`2 getExpressions) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 458
   at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 308
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Boolean useAutomaticTransactionManagement) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 157
   at Logary.Configuration.Migrations.migrateUp(DBConf conf, FSharpFunc`2 processorFac)
   at LogConf.migrate@28.Invoke(Unit unitVar0) in C:\msys64\home\beau.trepp\net\fpsrest\dotnet\src\BridgeFlow\LogConf.fs:line 31
   at LogConf.migrate@28-2.Do() in C:\msys64\home\beau.trepp\net\fpsrest\dotnet\src\BridgeFlow\LogConf.fs:line 28
   at Hopac.Core.JobThunk`1.DoJob(Worker& wr, Cont`1 xK)
   at Hopac.Infixes.op_GreaterGreaterMinusDot@204.DoJob(Worker& wr, Cont`1 aK)
   at Hopac.Job.catch@1149.DoJob(Worker& wr, Cont`1 aK)
   at Hopac.Core.JobCont`2.DoJob(Worker& wr, Cont`1 yK)
   at Hopac.Core.Worker.RunOnThisThread[T](Scheduler sr, Job`1 tJ, Cont`1 tK)
```

**Comment by haf** [comment]
@btrepp That's a nice catch. I think I had some sqlite unit tests for this but it probably didn't catch it.

**Comment by btrepp** [comment]
We moved to using influxdbs target as I had trouble setting up logary to build under windows (have been meaning to revisit this)

**Comment by haf** [comment]
ok, I'm keeping this issue open for a little bit.

**Comment by haf** [comment]
One exception:

```
0:00: Open Connection [Logary]
[11:02:01 WRN] Exception from supervised job, restarting in 6400 ms. <Logary.Target(db)>
System.DllNotFoundException: SQLite.Interop.dll
  at (wrapper managed-to-native) System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(System.Data.SQLite.SQLiteConfigOpsEnum)

```

@btrepp  Logary compiles great on Windows now, so if you want to revisit this, I've bumped the DB target tests (see above)
