### ISSUE TITLE
Cannot push — 400 Bad Request from nuget.org

### ISSUE THREAD

**Issue by haf** [logary/logary#383]
```
Pushing package /Users/h/dev/logibit/logary/src/targets/Logary.Targets.InfluxDb/bin/Logary.Targets.InfluxDb.5.0.0-beta.29.nupkg to https://nuget.org/api/v2/package - trial 1
Could not push /Users/h/dev/logibit/logary/src/Logary.CSharp/bin/Logary.CSharp.5.0.0-beta.29.nupkg: Request to 'https://www.nuget.org/api/v2/package' failed with: 400 BadRequest — Bad Request
..

Could not push ./src/ingestion/Logary.Ingestion.UDP/bin/Logary.Ingestion.UDP.5.0.0-beta.29.nupkg: Request to 'https://www.nuget.org/api/v2/package' failed with: 400 BadRequest — Bad Request
Pushing package ./src/ingestion/Logary.Ingestion.UDP/bin/Logary.Ingestion.UDP.5.0.0-beta.29.nupkg to https://nuget.org/api/v2/package - trial 5
No authorization found in config file.
Request failed with '400': 'https://www.nuget.org/api/v2/package'
Performance:
 - Runtime: 8 seconds
Paket failed with
-> RequestFailedException: Request to 'https://www.nuget.org/api/v2/package' failed with: 400 BadRequest — Bad Request
   StackTrace:
        at Paket.NetUtils.failIfNoSuccess@219-5.Invoke(RequestFailedInfo _arg1) in C:\code\Paket\src\Paket.Core\Common\NetUtils.fs:line 219
        at Microsoft.FSharp.Control.AsyncBuilderImpl.args@506-1.Invoke(a a)
     --- End of stack trace from previous location where exception was thrown ---
        at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
        at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
        at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
        at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
        at Paket.NetUtils.HttpClient.UploadFileAsMultipart(HttpClient x, Uri url, String filename) in C:\code\Paket\src\Paket.Core\Common\NetUtils.fs:line 336
        at Paket.RemoteUpload.uploadWithHttpClient@52(String url, String apiKey, String clientVersion, String packageFileName, FSharpOption`1 authOpt, Unit unitVar0) in C:\code\Paket\src\Paket.Core\Dependencies\RemoteUpload.fs:line 57
        at Paket.RemoteUpload.push@38(Int32 maxTrials, String url, String apiKey, String clientVersion, String packageFileName, FSharpTypeFunc tracefnVerbose, Int32 trial) in C:\code\Paket\src\Paket.Core\Dependencies\RemoteUpload.fs:line 73
        at Paket.RemoteUpload.push@38(Int32 maxTrials, String url, String apiKey, String clientVersion, String packageFileName, FSharpTypeFunc tracefnVerbose, Int32 trial) in C:\code\Paket\src\Paket.Core\Dependencies\RemoteUpload.fs:line 97
        at Paket.RemoteUpload.push@38(Int32 maxTrials, String url, String apiKey, String clientVersion, String packageFileName, FSharpTypeFunc tracefnVerbose, Int32 trial) in C:\code\Paket\src\Paket.Core\Dependencies\RemoteUpload.fs:line 97
        at Paket.RemoteUpload.push@38(Int32 maxTrials, String url, String apiKey, String clientVersion, String packageFileName, FSharpTypeFunc tracefnVerbose, Int32 trial) in C:\code\Paket\src\Paket.Core\Dependencies\RemoteUpload.fs:line 97
        at Paket.RemoteUpload.push@38(Int32 maxTrials, String url, String apiKey, String clientVersion, String packageFileName, FSharpTypeFunc tracefnVerbose, Int32 trial) in C:\code\Paket\src\Paket.Core\Dependencies\RemoteUpload.fs:line 97
        at Paket.RemoteUpload.Push(Int32 maxTrials, String url, String apiKey, String clientVersion, String packageFileName) in C:\code\Paket\src\Paket.Core\Dependencies\RemoteUpload.fs:line 98
        at Paket.Dependencies.Push[a](String packageFileName, FSharpOption`1 url, FSharpOption`1 apiKey, FSharpOption`1 endPoint, FSharpOption`1 paketVersion, FSharpOption`1 maxTrials) in C:\code\Paket\src\Paket.Core\PublicAPI.fs:line 769
        at Paket.Program.push[a](a paketVersion, ParseResults`1 results) in C:\code\Paket\src\Paket\Program.fs:line 728
        at Paket.Program.handleCommand@837-24.Invoke(ParseResults`1 results) in C:\code\Paket\src\Paket\Program.fs:line 837
        at Paket.Program.processWithValidationEx$cont@42[a](Boolean silent, FSharpFunc`2 commandF, a result, Unit unitVar) in C:\code\Paket\src\Paket\Program.fs:line 43
        at Paket.Program.processWithValidationEx[a](FSharpFunc`2 printUsage, Boolean silent, FSharpFunc`2 validateF, FSharpFunc`2 commandF, a result) in C:\code\Paket\src\Paket\Program.fs:line 35
        at Paket.Program.handleCommand(Boolean silent, Command command) in C:\code\Paket\src\Paket\Program.fs:line 837
        at Paket.Program.main() in C:\code\Paket\src\Paket\Program.fs:line 909
```

**Comment by lust4life** [comment]
seems a issue with paket .net core version https://github.com/fsprojects/Paket/issues/3458

**Comment by inosik** [comment]
This should be fixed by fsprojects/Paket#3466.

**Comment by lust4life** [comment]
@haf  seems fix pr in paket has been merged and released, maybe push is ok now, and FYI , things in https://github.com/logary/logary/pull/381#issuecomment-449556060 has been merged too.

**Comment by haf** [comment]
@lust4life Thanks! Will release tonight!

**Comment by haf** [comment]
Upgraded dependency on master.
