### ISSUE TITLE
Paket Pack

### ISSUE THREAD

**Issue by jamesjrg** [logary/logary#74]
# Last modified date of FSharp.Actor.dll is in 2030

The last modified fate of FSharp.Actor.dll (built from https://github.com/logary/FSharp.Actor-logary) has a last modified date of 15/12/2030,.

This means any project referencing it is always rebuilt by Visual Studio regardless of whether the source files have actually changed.

The same problem affects Newtonsoft.Json.FSharp (which has a modified date in 2068).

**Comment by haf** [comment]
Unfortunately, half a year later, @nuget still haven't fixed their bug: https://github.com/NuGet/Home/issues/624

This can be solved by moving to `paket pack`; and I have a failing test [here](https://github.com/Albacore/albacore/commit/c0d5d74bc7aed00a6b1f8fc447ba87a9bc11d31f) that someone needs to finish for using paket pack instead.

**Comment by jamesjrg** [comment]
How come it doesn't affect other nuget packages - does it only occur on Mono?

**Comment by haf** [comment]
Yes, only on unix machines. Many still do their publishes from Windows.

**Comment by haf** [comment]
Or maybe my computer is jinxed. That could also be the case...

**Comment by jamesjrg** [comment]
I tried building it on a Debian VM but it didn't seem to work. It may be I'm missing some library or something:

```##teamcity[buildNumber '4']
##teamcity[setParameter name='build.version' value='3.3.4-rc.d71216']
##teamcity[setParameter name='build.version.formal' value='3.3.4']
mono tools/paket.exe restore
0 seconds - ready.
xbuild /verbosity:minimal /property:Configuration=Release src/Logary.sln
XBuild Engine Version 12.0
Mono, Version 4.0.3.0
Copyright (C) 2005-2013 Various Mono authors
                Configuration: Release Platform: AnyCPU
        Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/Logary/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/Logary/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/Logary/Formatting.fs(40,11): warning FS0025: Incomplete pattern matches on this expression. For example, the value '[|_; _; _|]' may indicate a case not covered by the pattern(s).
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/targets/Logary.Targets.Riemann/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/targets/Logary.Targets.Riemann/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/targets/Logary.Targets.Zipkin/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/targets/Logary.Targets.Zipkin/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/targets/Logary.Targets.DB/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/targets/Logary.Targets.DB/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/targets/Logary.Targets.Dash/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/targets/Logary.Targets.Dash/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/targets/Logary.Targets.NLog/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/targets/Logary.Targets.NLog/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/targets/Logary.Targets.ElmahIO/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/targets/Logary.Targets.ElmahIO/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/targets/Logary.Targets.Loggr/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/targets/Logary.Targets.Loggr/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/targets/Logary.Targets.Logentries/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/targets/Logary.Targets.Logentries/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
rake aborted!
Albacore::CommandFailedError: Command failed with status (1):
  xbuild /verbosity:minimal /property:Configuration=Release src/Logary.sln
XBuild Engine Version 12.0
Mono, Version 4.0.3.0
Copyright (C) 2005-2013 Various Mono authors
                Configuration: Release Platform: AnyCPU
        Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/Logary/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/Logary/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/Logary/Formatting.fs(40,11): warning FS0025: Incomplete pattern matches on this expression. For example, the value '[|_; _; _|]' may indicate a case not covered by the pattern(s).
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/targets/Logary.Targets.Riemann/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/targets/Logary.Targets.Riemann/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/targets/Logary.Targets.Zipkin/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/targets/Logary.Targets.Zipkin/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/targets/Logary.Targets.DB/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/targets/Logary.Targets.DB/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/targets/Logary.Targets.Dash/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/targets/Logary.Targets.Dash/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/targets/Logary.Targets.NLog/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/targets/Logary.Targets.NLog/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/targets/Logary.Targets.ElmahIO/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/targets/Logary.Targets.ElmahIO/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/targets/Logary.Targets.Loggr/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/targets/Logary.Targets.Loggr/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/targets/Logary.Targets.Logentries/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/targets/Logary.Targets.Logentries/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/targets/Logary.Targets.Mailgun/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/targets/Logary.Targets.Mailgun/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/adapters/Logary.Adapters.Topshelf/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/adapters/Logary.Adapters.Topshelf/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/adapters/Logary.Adapters.log4net/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/adapters/Logary.Adapters.log4net/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/services/Logary.Services.SuaveReporter/Script.fsx(14,1): warning FS0211: The search directory '/home/vagrant/repos/logary/src/services/Logary.Services.SuaveReporter/bin/Debug' could not be found
/home/vagrant/repos/logary/src/services/Logary.Services.SuaveReporter/Script.fsx(15,1): error FS0078: Unable to find the file 'bin/Debug/Logary.dll' in any of↔ /usr/lib/mono/4.5↔ /home/vagrant/repos/logary/src/services/Logary.Services.SuaveReporter/../../../packages/FParsec/lib/net40-client↔ /home/vagrant/repos/logary/src/services/Logary.Services.SuaveReporter↔ /home/vagrant/repos/logary/packages/FSharp.Core/lib/net40
Configuration: Release Platform: AnyCPU
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/tests/Logary.Tests/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/tests/Logary.Tests/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
/var/lib/gems/2.1.0/gems/albacore-2.4.3/lib/albacore/cross_platform_cmd.rb:263:in `raise_failure'
/var/lib/gems/2.1.0/gems/albacore-2.4.3/lib/albacore/cross_platform_cmd.rb:242:in `block in handler_with_message'
/var/lib/gems/2.1.0/gems/albacore-2.4.3/lib/albacore/cross_platform_cmd.rb:111:in `call'
/var/lib/gems/2.1.0/gems/albacore-2.4.3/lib/albacore/cross_platform_cmd.rb:111:in `block in system'
/var/lib/gems/2.1.0/gems/albacore-2.4.3/lib/albacore/cross_platform_cmd.rb:247:in `handle_not_found'
/var/lib/gems/2.1.0/gems/albacore-2.4.3/lib/albacore/cross_platform_cmd.rb:87:in `system'
/var/lib/gems/2.1.0/gems/albacore-2.4.3/lib/albacore/task_types/build.rb:20:in `execute'
/var/lib/gems/2.1.0/gems/albacore-2.4.3/lib/albacore/task_types/build.rb:212:in `execute'
/var/lib/gems/2.1.0/gems/albacore-2.4.3/lib/albacore/dsl.rb:45:in `block in build'
Tasks: TOP => default => tests => build
(See full trace by running task with --trace)
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/targets/Logary.Targets.Mailgun/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/targets/Logary.Targets.Mailgun/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/adapters/Logary.Adapters.Topshelf/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/adapters/Logary.Adapters.Topshelf/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/adapters/Logary.Adapters.log4net/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/adapters/Logary.Adapters.log4net/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/services/Logary.Services.SuaveReporter/Script.fsx(14,1): warning FS0211: The search directory '/home/vagrant/repos/logary/src/services/Logary.Services.SuaveReporter/bin/Debug' could not be found
/home/vagrant/repos/logary/src/services/Logary.Services.SuaveReporter/Script.fsx(15,1): error FS0078: Unable to find the file 'bin/Debug/Logary.dll' in any of↔ /usr/lib/mono/4.5↔ /home/vagrant/repos/logary/src/services/Logary.Services.SuaveReporter/../../../packages/FParsec/lib/net40-client↔ /home/vagrant/repos/logary/src/services/Logary.Services.SuaveReporter↔ /home/vagrant/repos/logary/packages/FSharp.Core/lib/net40
Configuration: Release Platform: AnyCPU
Configuration: Release Platform: AnyCPU
/home/vagrant/repos/logary/src/tests/Logary.Tests/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 135 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
/home/vagrant/repos/logary/src/tests/Logary.Tests/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 227 in table 'itypars' of assembly 'FSharp.Actor, Version=0.0.1.0, Culture=neutral, PublicKeyToken=9adf1a27c1f9599c'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '3.3.4-rc.d71216', but this value is invalid and has been ignored```

**Comment by haf** [comment]
It was a bug in the F# compiler. When you recompile you need to do a clean recompile for it to work.

**Comment by haf** [comment]
I've updated the title of this issue to match the recommended solution.

Finishing this branch solves this issue: https://github.com/Albacore/albacore/tree/feature/paket-pack

**Comment by haf** [comment]
Closing due to lack of activity.
